version: '3'

tasks:
  default:
    desc: "Run the default"
    deps: [lite]

  lite:
    desc: "Delete hidden files in content dir and run the jupyter-lite service"
    cmds:
      - "rm -rf ./content/.*"
      - "docker compose up jupyter-lite"

  lab:
    desc: "Run Jupyter Lab"
    cmds:
      - "docker compose up jupyter-lab"

  down:
    desc: "Brings down any docker compose services"
    cmds:
      - "docker compose down"

  bash:
    desc: "Connect to container's prompt"
    cmds:
      - "docker run --rm -it -v $(pwd)/content:/content -p 8080:8080 --entrypoint '/bin/bash' my-app || true"

