version: '3'

tasks:

  default:
    cmds:
      - echo Running default TRALA TRALA TRALA
    deps: [from-home]


  run:
    /run.sh
    # jupyter-lite build --contents /content --output-dir dist && cd dist && jupyter-lite serve --port=8080

  from-home:
    cmds:
      - pwd

  from-working-directory:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - pwd